### ISSUE TITLE
Clearer definition?

### ISSUE THREAD

**Issue by impressivewebs** [Wisembly/bloader.js#1]
Hi, I'm not sure I understand what exactly your tool does. Is this a loading indicator? Or something more? Can you provide a succinct definition in the readme that states exactly what it is? Thanks.

**Comment by guillaumepotier** [comment]
Hi there, thanks for your interest into Bloader :)

I updated REAMDE to state better what Bloader is and what it mainly does. Feel free to ask any other question here if it is not still clear enough ;)

Best

**Comment by impressivewebs** [comment]
Cool, thanks! I'll probably include it in my newsletter: [Web Tools Weekly](http://webtoolsweekly.com/), which is why I was asking. :)
